/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practico_6.formularios;

import practico_6.entidades.*;

/**
 *
 * @author Usuario
 */
public class FormPrincipal extends javax.swing.JFrame {
    private Directorio directorio = new Directorio();


    
    /**
     * Creates new form FormPrincipal
     */
    public FormPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jdpEscritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmClientes = new javax.swing.JMenu();
        jmiBuscar = new javax.swing.JMenuItem();
        jmiBuscarTel = new javax.swing.JMenuItem();
        jmiBuscarApe = new javax.swing.JMenuItem();
        jmEditar = new javax.swing.JMenu();
        jmiAgregar = new javax.swing.JMenuItem();
        jmiBorrar = new javax.swing.JMenuItem();
        jMSalir = new javax.swing.JMenu();
        jMiSalir = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem5.setText("jMenuItem5");

        jMenuItem2.setText("jMenuItem2");

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem4.setText("jMenuItem4");

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("jMenu5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(610, 400));

        javax.swing.GroupLayout jdpEscritorioLayout = new javax.swing.GroupLayout(jdpEscritorio);
        jdpEscritorio.setLayout(jdpEscritorioLayout);
        jdpEscritorioLayout.setHorizontalGroup(
            jdpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 621, Short.MAX_VALUE)
        );
        jdpEscritorioLayout.setVerticalGroup(
            jdpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 335, Short.MAX_VALUE)
        );

        jMenuBar1.setNextFocusableComponent(jmClientes);

        jmClientes.setText("Clientes");

        jmiBuscar.setText("Buscar clientes");
        jmiBuscar.setPreferredSize(new java.awt.Dimension(150, 22));
        jmiBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiBuscarActionPerformed(evt);
            }
        });
        jmClientes.add(jmiBuscar);

        jmiBuscarTel.setText("Buscar por telefono");
        jmiBuscarTel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jmiBuscarTel.setPreferredSize(new java.awt.Dimension(125, 22));
        jmiBuscarTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiBuscarTelActionPerformed(evt);
            }
        });
        jmClientes.add(jmiBuscarTel);

        jmiBuscarApe.setText("Buscar por apellido");
        jmiBuscarApe.setPreferredSize(new java.awt.Dimension(125, 22));
        jmiBuscarApe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiBuscarApeActionPerformed(evt);
            }
        });
        jmClientes.add(jmiBuscarApe);

        jMenuBar1.add(jmClientes);

        jmEditar.setText("Editar");

        jmiAgregar.setText("Nuevo cliente");
        jmiAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAgregarActionPerformed(evt);
            }
        });
        jmEditar.add(jmiAgregar);

        jmiBorrar.setText("Eliminar cliente");
        jmiBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiBorrarActionPerformed(evt);
            }
        });
        jmEditar.add(jmiBorrar);

        jMenuBar1.add(jmEditar);

        jMSalir.setText("Salir");
        jMSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSalirActionPerformed(evt);
            }
        });
        jMSalir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jMSalirKeyPressed(evt);
            }
        });

        jMiSalir.setText("Salir del programa");
        jMiSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMiSalirActionPerformed(evt);
            }
        });
        jMSalir.add(jMiSalir);

        jMenuBar1.add(jMSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jdpEscritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jdpEscritorio)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAgregarActionPerformed
        jdpEscritorio.removeAll(); 
        jdpEscritorio.repaint();
        AgregarClientes ac = new AgregarClientes(directorio);
        ac.setVisible(true);
        jdpEscritorio.add(ac);
        jdpEscritorio.moveToFront(ac);
        ac.setFocusable(true);
        ac.requestFocusInWindow();
        ac.requestFocus(true);
        ac.requestFocus();
    }//GEN-LAST:event_jmiAgregarActionPerformed

    private void jmiBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiBorrarActionPerformed
        jdpEscritorio.removeAll(); 
        jdpEscritorio.repaint();
        BorrarClientes bc = new BorrarClientes(directorio);
        bc.setVisible(true);
        jdpEscritorio.add(bc);
        jdpEscritorio.moveToFront(bc);
        bc.setFocusable(true);
        bc.requestFocusInWindow();
        bc.requestFocus(true);
        bc.requestFocus();
    }//GEN-LAST:event_jmiBorrarActionPerformed

    private void jmiBuscarTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiBuscarTelActionPerformed
        jdpEscritorio.removeAll(); 
        jdpEscritorio.repaint();
        BuscarTelefono bt = new BuscarTelefono(directorio);
        bt.setVisible(true);
        jdpEscritorio.add(bt);
        jdpEscritorio.moveToFront(bt);
        bt.setFocusable(true);
        bt.requestFocusInWindow();
        bt.requestFocus(true);
        bt.requestFocus();
    }//GEN-LAST:event_jmiBuscarTelActionPerformed

    private void jMSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSalirActionPerformed
        
    }//GEN-LAST:event_jMSalirActionPerformed

    private void jMSalirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMSalirKeyPressed
        if (evt.getKeyCode()==evt.VK_ENTER) dispose();
    }//GEN-LAST:event_jMSalirKeyPressed

    private void jMiSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMiSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jMiSalirActionPerformed

    private void jmiBuscarApeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiBuscarApeActionPerformed
        jdpEscritorio.removeAll(); 
        jdpEscritorio.repaint();
        BuscarClientes bca = new BuscarClientes(directorio);
        bca.setVisible(true);
        jdpEscritorio.add(bca);
        jdpEscritorio.moveToFront(bca);
        bca.setFocusable(true);
        bca.requestFocusInWindow();
        bca.requestFocus(true);
        bca.requestFocus();
    }//GEN-LAST:event_jmiBuscarApeActionPerformed

    private void jmiBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiBuscarActionPerformed
        jdpEscritorio.removeAll(); 
        jdpEscritorio.repaint();
        BuscarCiudad bcc = new BuscarCiudad(directorio);
        bcc.setVisible(true);
        jdpEscritorio.add(bcc);
        jdpEscritorio.moveToFront(bcc);
        bcc.setFocusable(true);
        bcc.requestFocusInWindow();
        bcc.requestFocus(true);
        bcc.requestFocus();
    }//GEN-LAST:event_jmiBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
 
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMSalir;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMiSalir;
    private javax.swing.JDesktopPane jdpEscritorio;
    private javax.swing.JMenu jmClientes;
    private javax.swing.JMenu jmEditar;
    private javax.swing.JMenuItem jmiAgregar;
    private javax.swing.JMenuItem jmiBorrar;
    private javax.swing.JMenuItem jmiBuscar;
    private javax.swing.JMenuItem jmiBuscarApe;
    private javax.swing.JMenuItem jmiBuscarTel;
    // End of variables declaration//GEN-END:variables
}
