/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practico_6.formularios;

import practico_6.entidades.*;

/**
 *
 * @author Usuario
 */
public class FormPrincipal extends javax.swing.JFrame {
    private Directorio directorio = new Directorio();


    
    /**
     * Creates new form FormPrincipal
     */
    public FormPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jdpEscritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmClientes = new javax.swing.JMenu();
        jmiBuscarTel = new javax.swing.JMenuItem();
        jmiBuscarApe = new javax.swing.JMenuItem();
        jmiBuscar = new javax.swing.JMenuItem();
        jmEditar = new javax.swing.JMenu();
        jmiAgregar = new javax.swing.JMenuItem();
        jmiBorrar = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem5.setText("jMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jdpEscritorioLayout = new javax.swing.GroupLayout(jdpEscritorio);
        jdpEscritorio.setLayout(jdpEscritorioLayout);
        jdpEscritorioLayout.setHorizontalGroup(
            jdpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 386, Short.MAX_VALUE)
        );
        jdpEscritorioLayout.setVerticalGroup(
            jdpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 324, Short.MAX_VALUE)
        );

        jMenuBar1.setNextFocusableComponent(jmClientes);

        jmClientes.setText("Clientes");

        jmiBuscarTel.setText("Buscar por telefono");
        jmiBuscarTel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jmiBuscarTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiBuscarTelActionPerformed(evt);
            }
        });
        jmClientes.add(jmiBuscarTel);

        jmiBuscarApe.setText("Buscar por apellido");
        jmClientes.add(jmiBuscarApe);

        jmiBuscar.setText("Buscar clientes");
        jmClientes.add(jmiBuscar);

        jMenuBar1.add(jmClientes);

        jmEditar.setText("Editar");

        jmiAgregar.setText("Nuevo cliente");
        jmiAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAgregarActionPerformed(evt);
            }
        });
        jmEditar.add(jmiAgregar);

        jmiBorrar.setText("Eliminar cliente");
        jmiBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiBorrarActionPerformed(evt);
            }
        });
        jmEditar.add(jmiBorrar);

        jMenuBar1.add(jmEditar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jdpEscritorio)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jdpEscritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAgregarActionPerformed
        jdpEscritorio.removeAll(); 
        jdpEscritorio.repaint();
        AgregarClientes ac = new AgregarClientes(directorio);
        ac.setVisible(true);
        jdpEscritorio.add(ac);
        jdpEscritorio.moveToFront(ac);
    }//GEN-LAST:event_jmiAgregarActionPerformed

    private void jmiBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiBorrarActionPerformed
        jdpEscritorio.removeAll(); 
        jdpEscritorio.repaint();
        BorrarClientes bc = new BorrarClientes(directorio);
        bc.setVisible(true);
        jdpEscritorio.add(bc);
        jdpEscritorio.moveToFront(bc);
    }//GEN-LAST:event_jmiBorrarActionPerformed

    private void jmiBuscarTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiBuscarTelActionPerformed
        jdpEscritorio.removeAll(); 
        jdpEscritorio.repaint();
        BuscarTelefono bt = new BuscarTelefono();
        bt.setVisible(true);
        jdpEscritorio.add(bt);
        jdpEscritorio.moveToFront(bt);
    }//GEN-LAST:event_jmiBuscarTelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
 
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JDesktopPane jdpEscritorio;
    private javax.swing.JMenu jmClientes;
    private javax.swing.JMenu jmEditar;
    private javax.swing.JMenuItem jmiAgregar;
    private javax.swing.JMenuItem jmiBorrar;
    private javax.swing.JMenuItem jmiBuscar;
    private javax.swing.JMenuItem jmiBuscarApe;
    private javax.swing.JMenuItem jmiBuscarTel;
    // End of variables declaration//GEN-END:variables
}
